#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-collections
Version  : 0.3.8
Release  : 39
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/collections_0.3.8.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/collections_0.3.8.tar.gz
Summary  : High Performance Container Data Types
Group    : Development/Tools
License  : MIT
Requires: R-collections-lib = %{version}-%{release}
BuildRequires : buildreq-R

%description
as queues, stacks, deques, dicts and ordered dicts. Benchmarks

%package lib
Summary: lib components for the R-collections package.
Group: Libraries

%description lib
lib components for the R-collections package.


%prep
%setup -q -n collections
pushd ..
cp -a collections buildavx2
popd
pushd ..
cp -a collections buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746713895

%install
export SOURCE_DATE_EPOCH=1746713895
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/collections/DESCRIPTION
/usr/lib64/R/library/collections/INDEX
/usr/lib64/R/library/collections/LICENSE
/usr/lib64/R/library/collections/Meta/Rd.rds
/usr/lib64/R/library/collections/Meta/features.rds
/usr/lib64/R/library/collections/Meta/hsearch.rds
/usr/lib64/R/library/collections/Meta/links.rds
/usr/lib64/R/library/collections/Meta/nsInfo.rds
/usr/lib64/R/library/collections/Meta/package.rds
/usr/lib64/R/library/collections/NAMESPACE
/usr/lib64/R/library/collections/R/collections
/usr/lib64/R/library/collections/R/collections.rdb
/usr/lib64/R/library/collections/R/collections.rdx
/usr/lib64/R/library/collections/help/AnIndex
/usr/lib64/R/library/collections/help/aliases.rds
/usr/lib64/R/library/collections/help/collections.rdb
/usr/lib64/R/library/collections/help/collections.rdx
/usr/lib64/R/library/collections/help/paths.rds
/usr/lib64/R/library/collections/html/00Index.html
/usr/lib64/R/library/collections/html/R.css
/usr/lib64/R/library/collections/tests/testthat.R
/usr/lib64/R/library/collections/tests/testthat/test-cls.R
/usr/lib64/R/library/collections/tests/testthat/test-deque.R
/usr/lib64/R/library/collections/tests/testthat/test-dict.R
/usr/lib64/R/library/collections/tests/testthat/test-ordered_dict.R
/usr/lib64/R/library/collections/tests/testthat/test-priority_queue.R
/usr/lib64/R/library/collections/tests/testthat/test-queue.R
/usr/lib64/R/library/collections/tests/testthat/test-stack.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/collections/libs/collections.so
/V4/usr/lib64/R/library/collections/libs/collections.so
/usr/lib64/R/library/collections/libs/collections.so
